#!/usr/bin/env python3
from __future__ import annotations

import re
import struct
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPELL_DBC = ROOT / "spell" / "Spell.dbc"
OUT = ROOT / "Data" / "SpellRaw_Epoch.lua"

SPELL_DATA_FILES = [
    ROOT / "Data" / "SpellData_52.lua",
    ROOT / "Data" / "SpellData_Season.lua",
    ROOT / "Data" / "SpellData_Epoch.lua",
]

ID_RE = re.compile(r"\[(\d+)\]\s*=")

# Project Epoch's Spell.dbc follows the WotLK 3.3.5 layout.
SPELL_NAME_FIELD = 136
SPELL_RANK_FIELD = 153
SPELL_DESCRIPTION_FIELD = 170
SPELL_AURA_DESCRIPTION_FIELD = 187


def lua_quote(value: str) -> str:
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    value = value.replace("\r\n", "\n").replace("\r", "\n")
    value = value.replace("\n", "\\n")
    return f'"{value}"'


def translated_spell_ids() -> set[int]:
    ids: set[int] = set()
    for path in SPELL_DATA_FILES:
        if not path.exists():
            continue
        ids.update(int(match.group(1)) for match in ID_RE.finditer(path.read_text(encoding="utf-8")))
    return ids


def read_cstring(strings: bytes, offset: int, string_size: int) -> str:
    if offset >= string_size:
        return ""
    end = strings.find(b"\0", offset)
    if end < 0:
        end = len(strings)
    return strings[offset:end].decode("utf-8", errors="replace")


def read_spell_dbc(ids: set[int]) -> list[tuple[int, str, str, str, str]]:
    data = SPELL_DBC.read_bytes()
    magic, record_count, field_count, record_size, string_size = struct.unpack_from("<4sIIII", data, 0)
    if magic != b"WDBC":
        raise ValueError(f"Not a WDBC file: {SPELL_DBC}")
    if field_count <= SPELL_AURA_DESCRIPTION_FIELD:
        raise ValueError(f"Unexpected Spell.dbc field count: {field_count}")

    record_start = 20
    string_start = record_start + record_count * record_size
    strings = data[string_start : string_start + string_size]
    rows: list[tuple[int, str, str, str, str]] = []

    for record_index in range(record_count):
        record_offset = record_start + record_index * record_size
        values = struct.unpack_from("<" + "I" * field_count, data, record_offset)
        spell_id = values[0]
        if spell_id not in ids:
            continue

        name = read_cstring(strings, values[SPELL_NAME_FIELD], string_size)
        if not name or "Word of Recall" in name:
            continue

        rank = read_cstring(strings, values[SPELL_RANK_FIELD], string_size)
        description = read_cstring(strings, values[SPELL_DESCRIPTION_FIELD], string_size)
        aura_description = read_cstring(strings, values[SPELL_AURA_DESCRIPTION_FIELD], string_size)
        rows.append((spell_id, name, rank, description, aura_description))

    rows.sort(key=lambda row: row[0])
    return rows


def write_lua(rows: list[tuple[int, str, str, str, str]]) -> None:
    lines = [
        "-- Auto-generated by Tools/generate_epoch_spell_raw.py from spell/Spell.dbc.",
        "-- English raw spell names let EpochCN map client spell text back to existing Chinese translations.",
        "function LoadEpochCNSpellRawData()",
        "    EpochCN_SpellRawData = {",
    ]

    for spell_id, name, rank, description, aura_description in rows:
        fields = [lua_quote(name)]
        if rank or description or aura_description:
            fields.append(lua_quote(rank))
        if description or aura_description:
            fields.append(lua_quote(description))
        if aura_description:
            fields.append(lua_quote(aura_description))
        lines.append(f"        [{spell_id}] = {{{', '.join(fields)}}},")

    lines.extend([
        "    }",
        "end",
        "",
    ])
    OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ids = translated_spell_ids()
    rows = read_spell_dbc(ids)
    write_lua(rows)
    print(f"Wrote {OUT} with {len(rows)} raw spell rows for {len(ids)} translated spell ids.")


if __name__ == "__main__":
    main()
